export const LOAD_PAGE = 'LOAD_PAGE';
export const DERP = 'DERP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUEST_TOKEN = 'LOGIN_REQUEST_TOKEN';
export const LOGIN_REQUEST_TOKEN_FAILED = 'LOGIN_REQUEST_TOKEN_FAILED';
